import {AppShell} from "@/components/AppShell";
import {WorkspaceForm} from "@/components/WorkspaceForm";
import {EditBatchForm} from "@/components/EditBatchForm";
import {DataTable} from "@/components/DataTable";
import {trainingData,options} from "@/lib/workspace";
import {requireUser} from "@/lib/auth";
export default async function TrainingPage(){const user=await requireUser("training");const d=await trainingData();const staff=user.role!=="trainer";const batches=options(d.batches);const students=options(d.parties.filter(r=>(r.roles as string[]).includes("student")));const trainers=options(d.parties.filter(r=>(r.roles as string[]).includes("trainer")));return <AppShell breadcrumb="Training operations"><div className="mx-auto max-w-6xl space-y-7 px-6 py-8"><header><p className="eyebrow">02 / DELIVERY</p><h1 className="mt-3 text-3xl font-semibold">{staff?"Training operations":"Your assigned batches"}</h1><p className="mt-3 text-sm text-slate-500">{staff?"Coordinate courses, trainers and learners. Keep delivery progress visible.":"Record attendance for the learners in your assigned programmes."}</p></header><DataTable columns={["Batch","Course","Trainer","Dates","Status"]} rows={d.batches.map(r=>[String(r.name),String(r.title),String(r.trainer??"Unassigned"),`${r.starts_on??"TBD"} – ${r.ends_on??"TBD"}`,String(r.status)])}/><div className="grid items-start gap-4 lg:grid-cols-2">
 {staff&&<><WorkspaceForm title="Add a learner or trainer" kind="party" fields={[{name:"name",label:"Name"},{name:"email",label:"Email",type:"email",required:false},{name:"phone",label:"Phone",required:false},{name:"partyRole",label:"Profile type",options:[{value:"student",label:"Learner"},{value:"trainer",label:"Trainer"},{value:"corporate_buyer",label:"Corporate buyer"}]}]}/>
 <WorkspaceForm title="Add a course" kind="course" fields={[{name:"title",label:"Course title"},{name:"amount",label:"Default price (INR)",type:"number",min:"0.01"}]}/>
 <WorkspaceForm title="Create a batch" kind="batch" fields={[{name:"name",label:"Batch name"},{name:"courseId",label:"Course",options:options(d.courses)},{name:"trainerId",label:"Trainer",options:trainers,required:false},{name:"enquiryId",label:"Won enquiry",options:options(d.leads),required:false},{name:"location",label:"Location",required:false},{name:"startsOn",label:"Start date",type:"date",required:false},{name:"endsOn",label:"End date",type:"date",required:false}]}/>
 <WorkspaceForm title="Enroll a learner" kind="enroll" fields={[{name:"batchId",label:"Batch",options:batches},{name:"studentId",label:"Learner",options:students}]}/>
 <WorkspaceForm title="Update batch status" kind="batchStatus" fields={[{name:"batchId",label:"Batch",options:batches},{name:"status",label:"Status",options:["planned","running","completed","cancelled"].map(v=>({value:v,label:v}))}]}/>
 <EditBatchForm batches={d.batches.map(r=>({id:String(r.id),name:String(r.name),location:(r.location as string|null)??null,starts_on:(r.starts_on as string|null)??null,ends_on:(r.ends_on as string|null)??null}))}/></>}
 <WorkspaceForm title="Mark attendance" kind="attendance" fields={[{name:"enrollmentId",label:"Learner / batch",options:d.enrollments.map(r=>({value:String(r.id),label:`${r.student} / ${r.batch}`}))},{name:"sessionDate",label:"Session date",type:"date"},{name:"present",label:"Attendance",options:[{value:"true",label:"Present"},{value:"false",label:"Absent"}]}]}/></div>
 <section><h2 className="mb-3 text-lg font-semibold">Enrollments</h2><DataTable columns={["Learner","Batch","Status"]} rows={d.enrollments.map(r=>[String(r.student),String(r.batch),String(r.status)])}/></section>
 <section><h2 className="mb-3 text-lg font-semibold">Attendance history</h2><DataTable columns={["Date","Learner","Batch","Attendance"]} rows={d.attendance.map(r=>[String(r.session_date),String(r.student),String(r.batch),r.present?"Present":"Absent"])}/></section>
 </div></AppShell>;}
