import {AppShell} from "@/components/AppShell";
import {WorkspaceForm} from "@/components/WorkspaceForm";
import {RefundForm} from "@/components/RefundForm";
import {DataTable} from "@/components/DataTable";
import {financeData,options} from "@/lib/workspace";
import {formatINR} from "@/lib/format";
export default async function FinancePage(){const d=await financeData();const batches=options(d.batches);return <AppShell breadcrumb="Billing & payments"><div className="mx-auto max-w-6xl space-y-7 px-6 py-8"><header><p className="eyebrow">03 / FINANCE</p><h1 className="mt-3 text-3xl font-semibold">Keep every rupee<br/>connected to its batch.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Amounts follow the existing pre-tax programme ledger. GST rates are recorded separately. Settle an existing installment to avoid recording the same payment twice.</p></header><DataTable columns={["Customer / batch","Invoice","Invoiced","Collected","Balance","Status"]} statusIndex={5} rows={d.invoices.map(r=>[`${r.name} / ${r.batch}`,String(r.id).slice(0,8),formatINR(String(r.amount)),formatINR(String(r.paid)),formatINR(Number(r.amount)-Number(r.paid)),String(r.status)])}/><div className="grid items-start gap-4 lg:grid-cols-2">
 <WorkspaceForm title="Issue an invoice" kind="invoice" description="Creates the invoice and one scheduled installment together." fields={[{name:"partyId",label:"Customer",options:options(d.parties)},{name:"batchId",label:"Batch",options:batches},{name:"amount",label:"Amount (INR, before GST)",type:"number",min:"0.01"},{name:"gstRate",label:"GST rate (%)",type:"number",min:"0",max:"100",value:"18"},{name:"dueOn",label:"Payment due date",type:"date"},{name:"description",label:"Description",required:false}]}/>
 <WorkspaceForm title="Settle an installment" kind="settle" description="Records receipt against an existing unpaid installment. Repeating the same settlement does not duplicate cash." fields={[{name:"paymentId",label:"Unpaid installment",options:d.payments.filter(r=>!r.paid_at).map(r=>({value:String(r.id),label:`${r.batch} / ${formatINR(String(r.amount))} / ${r.due_on??"No due date"}`}))},{name:"method",label:"Payment method",options:["bank","upi","card","cash"].map(v=>({value:v,label:v}))}]}/>
 <WorkspaceForm title="Record an unscheduled receipt" kind="payment" description="For invoices without a matching scheduled installment. Existing allocations and overpayments are checked." fields={[{name:"invoiceId",label:"Invoice",options:d.invoices.filter(r=>r.status!=="paid"&&r.status!=="void").map(r=>({value:String(r.id),label:`${r.name} / ${r.batch} / ${String(r.id).slice(0,8)}`}))},{name:"amount",label:"Amount (INR)",type:"number",min:"0.01"},{name:"method",label:"Payment method",options:["bank","upi","card","cash"].map(v=>({value:v,label:v}))}]}/>
 <WorkspaceForm title="Record a batch expense" kind="expense" fields={[{name:"batchId",label:"Batch",options:batches},{name:"category",label:"Category",options:["venue","travel","materials","marketing","other"].map(v=>({value:v,label:v}))},{name:"amount",label:"Amount (INR)",type:"number",min:"0.01"},{name:"vendor",label:"Vendor",required:false}]}/>
 <WorkspaceForm title="Record a trainer payment" kind="trainerPayment" fields={[{name:"batchId",label:"Batch",options:batches},{name:"trainerId",label:"Trainer",options:options(d.parties.filter(r=>(r.roles as string[]).includes("trainer")))},{name:"amount",label:"Amount (INR)",type:"number",min:"0.01"}]}/>
 <RefundForm payments={d.payments.filter(r=>r.paid_at&&r.method!=="refund").map(r=>({id:String(r.id),batch:String(r.batch),amount:String(r.amount),refunded:String(r.refunded)}))}/></div>
 <section><h2 className="mb-3 text-lg font-semibold">Installments & receipts</h2><DataTable columns={["Batch","Amount","Due date","Received","Method"]} rows={d.payments.filter(r=>r.method!=="refund").map(r=>[String(r.batch),formatINR(String(r.amount)),String(r.due_on??"—"),r.paid_at?String(r.paid_at).slice(0,10):"Outstanding",String(r.method??"—")])}/></section>
 <section><h2 className="mb-3 text-lg font-semibold">Refunds</h2><DataTable columns={["Batch","Amount","Refunded on"]} empty="No refunds recorded." rows={d.payments.filter(r=>r.method==="refund").map(r=>[String(r.batch),formatINR(String(Math.abs(Number(r.amount)))),r.paid_at?String(r.paid_at).slice(0,10):"—"])}/></section>
 </div></AppShell>;}
